# Generated by Django 3.0.5 on 2020-04-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('requirement', models.CharField(max_length=30)),
                ('launcher', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, unique=True)),
                ('team_members', models.TextField()),
                ('creator', models.CharField(max_length=15)),
                ('team_introduction', models.TextField()),
                ('activities', models.TextField()),
                ('previous_activities', models.TextField()),
                ('uploaded_person_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('create_time', models.DateTimeField()),
                ('sex', models.CharField(max_length=1)),
                ('image', models.BinaryField()),
                ('phone_number', models.CharField(max_length=15)),
                ('teams', models.TextField()),
                ('activities', models.TextField()),
                ('time_schedule', models.CharField(max_length=84)),
                ('self_introduction', models.TextField()),
                ('friends', models.TextField()),
            ],
        ),
    ]
