# Generated by Django 3.0.5 on 2020-04-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='team',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='activities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='previous_activities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='uploaded_person_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='activities',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='self_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='teams',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_schedule',
            field=models.CharField(max_length=84, null=True),
        ),
    ]
