# Generated by Django 3.0.4 on 2020-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_auto_20200424_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='participants',
            field=models.TextField(default='xxx'),
        ),
    ]
