# Generated by Django 3.0.4 on 2020-05-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_activities_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='participants',
            field=models.TextField(),
        ),
    ]
