# Generated by Django 3.0.4 on 2020-05-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_auto_20200502_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=10)),
                ('nick_name', models.CharField(max_length=10)),
            ],
        ),
    ]
