# Generated by Django 3.0.4 on 2020-05-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname',
            name='nick_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
