# Generated by Django 3.0.4 on 2020-05-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0009_users_to_add_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='to_add_friends',
            field=models.CharField(default='', max_length=200),
        ),
    ]
